- hosts: web
  become: yes

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ubuntu to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Create docker network
      command: docker network create app-network
      ignore_errors: yes

    # ---------------- CLEANUP FIRST ----------------
    - name: Remove old frontend container
      command: docker rm -f frontend
      ignore_errors: yes

    - name: Remove old backend container
      command: docker rm -f backend
      ignore_errors: yes

    - name: Remove old mongo container
      command: docker rm -f mongo
      ignore_errors: yes

    # ---------------- RUN MONGO FIRST ----------------
    - name: Run Mongo container
      command: >
        docker run -d
        --name mongo
        --network app-network
        mongo

    # ---------------- BACKEND ----------------
    - name: Run backend container
      command: >
        docker run -d
        --name backend
        --network app-network
        -p 5001:5001
        -e PORT=5001
        -e MONGO_URI=mongodb://mongo:27017/taskmanager
        sat9999/backend-app:latest

    # ---------------- FRONTEND ----------------
    - name: Run frontend container
      command: >
        docker run -d
        --name frontend
        --network app-network
        -p 3000:3000
        sat9999/frontend-app:latest
