name: Terraform EC2 Deploy

on:
  workflow_dispatch: 

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      # AWS LOGIN
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # TERRAFORM INSTALL
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # TERRAFORM INIT
      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      # TERRAFORM PLAN
      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform

      # TERRAFORM APPLY
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform
      
      # GET SERVER IP
      - name: Get Server IP
        id: tf
        run: |
          echo "ip=$(terraform output -raw server_ip)" >> $GITHUB_OUTPUT
        working-directory: terraform

      - name: Wait for EC2 to be fully ready (AWS status checks)
        run: |
          INSTANCE_ID=$(terraform output -raw instance_id)

            aws ec2 wait instance-status-ok \
              --instance-ids $INSTANCE_ID \
              --region us-east-1
        
            echo "EC2 status checks passed"

      # SSH KEY
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # INSTALL ANSIBLE
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install ansible -y

      # CREATE INVENTORY
      - name: Create Inventory
        run: |
          echo "[web]" > inventory.ini
          echo "${{ steps.tf.outputs.ip }} ansible_user=ubuntu" >> inventory.ini

      # DISABLE HOST CHECKING
      - name: Disable Host Checking
        run: |
          export ANSIBLE_HOST_KEY_CHECKING=False

      # RUN PLAYBOOK
      - name: Run Ansible
        run: |
          ansible-playbook -i inventory.ini ansible/playbook.yml
